# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf68895a70251dc0653610a74bddf95d93ad66f2d40b02b191b59dc042ebe7cca71a69bf2e02eb9edd60c96b9b5bccfa1edf75419276d0a645400a0bf91a95b3

test:
  secret_key_base: 896619658c83113aa1f7f0ef6c614a7660eeabc05409edbf5dd444f2791f7aeedd135f744e92c5ba92b6bc9d55957ce3ebad213bceb9fad39ce6b8f892c68784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
